apiVersion: v1
kind: Service
metadata:
  name: example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'nlb'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:999999999999:certificate/1c0cc978-0512-4f54-8912-76b70693c6ba
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: TCP
    targetPort: 'http'
  selector:
    function: serves-http
