apiVersion: v1
kind: Pod
metadata:
  name: 'httpd'
spec:
  containers:
  - name: 'httpd'
    image: docker.io/ovidiufeodorov/httpd:latest
    volumeMounts:
      - name: infra-playground-dev-8
        mountPath: /efs
        # subPath: ''
  volumes:
    - name: infra-playground-dev-8
      persistentVolumeClaim:
        claimName: infra-playground-dev-8
