apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cm-playground-efs-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: c3-cf-sc
  volumeName: cm-playground-efs-2
  resources:
    requests:
      storage: 1Gi
