apiVersion: v1
kind: Pod
metadata:
  name: httpd
  {{- if .Values.mapTransfer.annotations }}
  annotations:
    {{- range $annotation, $value := .Values.mapTransfer.annotations }}
    {{ $annotation }}: {{ $value | quote -}}
    {{ end }}
  {{- end }}
spec:
  containers:
    - name: httpd
      image: docker.io/ovidiufeodorov/httpd:latest
