apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 'http'
    nodePort: 18080
  selector:
    function: serves-http
  #sessionAffinity: ClientIP
