apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  ports:
  - port: 80
    name: 'a'
    protocol: TCP
    targetPort: 80
  - port: 81
    name: 'b'
    protocol: TCP
    targetPort: 81
  selector:
    function: serves-http