apiVersion: v1
kind: Pod
metadata:
  name: 'httpd'
spec:
  containers:
  - name: 'httpd'
    image: docker.io/ovidiufeodorov/httpd:latest
    volumeMounts:
      - name: 'httpd-local-root'
        mountPath: '/usr/local/apache2/htdocs'
  volumes:
    - name: 'httpd-local-root'
      hostPath:
        path: /Users/ovidiufeodorov/tmp/httpd-root
