apiVersion: v1
kind: Pod
metadata:
  name: 'loop'
spec:
  securityContext:
    runAsUser: 7777
    runAsGroup: 8888
  containers:
  - name: 'loop'
    image: experimental/loop:latest
    imagePullPolicy: IfNotPresent
