apiVersion: v1
kind: Secret
metadata:
  name: example
type: Opaque
stringData:
  kafka-truststore.jks: |
    blah
    blah2
---
apiVersion: v1
kind: Pod
metadata:
  name: 'httpd'
  labels:
    function: 'httpd'
spec:
  containers:
    - name: 'httpd'
      image: docker.io/ovidiufeodorov/httpd:latest
      volumeMounts:
        - name: example
          mountPath: /etc/example
          readOnly: true
  volumes:
    - name: example
      secret:
        secretName: example
        defaultMode: 0400




